'''OpenGL extension APPLE.rgb_422

This module customises the behaviour of the 
OpenGL.raw.GLES2.APPLE.rgb_422 to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/APPLE/rgb_422.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
import ctypes
from OpenGL.raw.GLES2 import _types, _glgets
from OpenGL.raw.GLES2.APPLE.rgb_422 import *
from OpenGL.raw.GLES2.APPLE.rgb_422 import _EXTENSION_NAME

def glInitRgb422APPLE():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )


### END AUTOGENERATED SECTION